remote_theme: "mmistakes/so-simple-theme@3.2.0"

skin: "/assets/css/skins/default.css"
title: "DikkeKlok.nl"
description: "Het beste voor je arm!"
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/logo/logo.png"
date_format: "%-d %B %Y"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  winkel:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post

# Site Author
author:
  name: Daan
  picture: "images/panda/panda-profile.png"
  email: "info@dikkeklok.nl"
  links:
    - title: Instagram
      url: https://instagram.com/dikkeklok
      icon: fab fa-instagram

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: Instagram
    url: https://instagram.com/dikkeklok
    icon: fab fa-instagram-square
  - title: RoadToRolex
    url: https://roadtorolex.nl
    icon: fas fa-road
